{
 "title": "Throughput",
 "description": "Micrometer Http throughput dashboard ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "SLA_REQUEST_TIME", "query": "0.5" }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri!~\"/actuator/.*\"}[1m]) / rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time of 50%, 75%, 90%, 95% of requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[1m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[1m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}